auto: true

markdown: kramdown
pygments: true
paginate: 10
paginate_path: "page:num"
permalink: pretty

title: 技术人生
url: http://lingxiankong.github.io
feed: /atom.xml
author_info: <a href="http://lingxiankong.github.io/">Lingxian Kong</a>
